-- Calendar day metrics
-- One row per user and date, used by the calendar and dashboard.

begin;

create table if not exists public.calendar_day_metrics (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  metric_date date not null,
  views integer not null default 0,
  reach integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint calendar_day_metrics_views_nonnegative check (views >= 0),
  constraint calendar_day_metrics_reach_nonnegative check (reach >= 0),
  constraint calendar_day_metrics_user_date_unique unique (user_id, metric_date)
);

create index if not exists calendar_day_metrics_user_id_idx
  on public.calendar_day_metrics (user_id);

create index if not exists calendar_day_metrics_metric_date_idx
  on public.calendar_day_metrics (metric_date);

create index if not exists calendar_day_metrics_user_date_idx
  on public.calendar_day_metrics (user_id, metric_date desc);

create or replace function public.calendar_day_metrics_set_updated_at()
returns trigger
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists calendar_day_metrics_set_updated_at on public.calendar_day_metrics;

create trigger calendar_day_metrics_set_updated_at
before update on public.calendar_day_metrics
for each row
execute function public.calendar_day_metrics_set_updated_at();

alter table public.calendar_day_metrics enable row level security;

drop policy if exists "calendar_day_metrics_select_own" on public.calendar_day_metrics;
drop policy if exists "calendar_day_metrics_insert_own" on public.calendar_day_metrics;
drop policy if exists "calendar_day_metrics_update_own" on public.calendar_day_metrics;
drop policy if exists "calendar_day_metrics_delete_own" on public.calendar_day_metrics;

create policy "calendar_day_metrics_select_own"
on public.calendar_day_metrics
for select
using (auth.role() = 'authenticated' and auth.uid() = user_id);

create policy "calendar_day_metrics_insert_own"
on public.calendar_day_metrics
for insert
with check (auth.role() = 'authenticated' and auth.uid() = user_id);

create policy "calendar_day_metrics_update_own"
on public.calendar_day_metrics
for update
using (auth.role() = 'authenticated' and auth.uid() = user_id)
with check (auth.role() = 'authenticated' and auth.uid() = user_id);

create policy "calendar_day_metrics_delete_own"
on public.calendar_day_metrics
for delete
using (auth.role() = 'authenticated' and auth.uid() = user_id);

grant select, insert, update, delete on public.calendar_day_metrics to anon, authenticated;

-- Seed the current June dataset for the demo users.
insert into public.calendar_day_metrics (user_id, metric_date, views, reach)
select seed.user_id, seed.metric_date, seed.views, seed.reach
from (
  values
    ('4b8a4d0f-6f9e-4c3d-9a1d-2e1f4d58d101'::uuid, date '2026-05-28', 7, 0),
    ('4b8a4d0f-6f9e-4c3d-9a1d-2e1f4d58d101'::uuid, date '2026-06-01', 20402, 0),
    ('4b8a4d0f-6f9e-4c3d-9a1d-2e1f4d58d101'::uuid, date '2026-06-02', 15174, 0),
    ('4b8a4d0f-6f9e-4c3d-9a1d-2e1f4d58d101'::uuid, date '2026-06-03', 16737, 0),
    ('4b8a4d0f-6f9e-4c3d-9a1d-2e1f4d58d101'::uuid, date '2026-06-04', 31422, 24362),
    ('4b8a4d0f-6f9e-4c3d-9a1d-2e1f4d58d101'::uuid, date '2026-06-05', 21423, 0),
    ('4b8a4d0f-6f9e-4c3d-9a1d-2e1f4d58d101'::uuid, date '2026-06-06', 10132, 0),
    ('4b8a4d0f-6f9e-4c3d-9a1d-2e1f4d58d101'::uuid, date '2026-06-07', 12167, 0),
    ('4b8a4d0f-6f9e-4c3d-9a1d-2e1f4d58d101'::uuid, date '2026-06-08', 17323, 0),
    ('4b8a4d0f-6f9e-4c3d-9a1d-2e1f4d58d101'::uuid, date '2026-06-09', 17298, 0),
    ('2c1b7d5f-88a4-4b7b-8cb5-7d8a6f5c2b02'::uuid, date '2026-05-28', 7, 0),
    ('2c1b7d5f-88a4-4b7b-8cb5-7d8a6f5c2b02'::uuid, date '2026-06-01', 20402, 0),
    ('2c1b7d5f-88a4-4b7b-8cb5-7d8a6f5c2b02'::uuid, date '2026-06-02', 15174, 0),
    ('2c1b7d5f-88a4-4b7b-8cb5-7d8a6f5c2b02'::uuid, date '2026-06-03', 16737, 0),
    ('2c1b7d5f-88a4-4b7b-8cb5-7d8a6f5c2b02'::uuid, date '2026-06-04', 31422, 24362),
    ('2c1b7d5f-88a4-4b7b-8cb5-7d8a6f5c2b02'::uuid, date '2026-06-05', 21423, 0),
    ('2c1b7d5f-88a4-4b7b-8cb5-7d8a6f5c2b02'::uuid, date '2026-06-06', 10132, 0),
    ('2c1b7d5f-88a4-4b7b-8cb5-7d8a6f5c2b02'::uuid, date '2026-06-07', 12167, 0),
    ('2c1b7d5f-88a4-4b7b-8cb5-7d8a6f5c2b02'::uuid, date '2026-06-08', 17323, 0),
    ('2c1b7d5f-88a4-4b7b-8cb5-7d8a6f5c2b02'::uuid, date '2026-06-09', 17298, 0),
    ('7d8a2c11-0f4e-4e7b-b0a9-3f9d77a1c303'::uuid, date '2026-05-28', 7, 0),
    ('7d8a2c11-0f4e-4e7b-b0a9-3f9d77a1c303'::uuid, date '2026-06-01', 20402, 0),
    ('7d8a2c11-0f4e-4e7b-b0a9-3f9d77a1c303'::uuid, date '2026-06-02', 15174, 0),
    ('7d8a2c11-0f4e-4e7b-b0a9-3f9d77a1c303'::uuid, date '2026-06-03', 16737, 0),
    ('7d8a2c11-0f4e-4e7b-b0a9-3f9d77a1c303'::uuid, date '2026-06-04', 31422, 24362),
    ('7d8a2c11-0f4e-4e7b-b0a9-3f9d77a1c303'::uuid, date '2026-06-05', 21423, 0),
    ('7d8a2c11-0f4e-4e7b-b0a9-3f9d77a1c303'::uuid, date '2026-06-06', 10132, 0),
    ('7d8a2c11-0f4e-4e7b-b0a9-3f9d77a1c303'::uuid, date '2026-06-07', 12167, 0),
    ('7d8a2c11-0f4e-4e7b-b0a9-3f9d77a1c303'::uuid, date '2026-06-08', 17323, 0),
    ('7d8a2c11-0f4e-4e7b-b0a9-3f9d77a1c303'::uuid, date '2026-06-09', 17298, 0)
) as seed(user_id, metric_date, views, reach)
on conflict (user_id, metric_date) do update
set
  views = excluded.views,
  reach = excluded.reach,
  updated_at = now();

commit;
