begin;

create schema if not exists backup;

create table if not exists public.team_profiles (
  id bigint primary key,
  user_id uuid unique,
  name text not null,
  role text not null,
  avatar text not null default '',
  specialty text not null default '',
  color text not null default '#e50914',
  stats jsonb not null default '{}'::jsonb,
  radar jsonb not null default '[]'::jsonb,
  monthly_posts jsonb not null default '[]'::jsonb,
  email text not null unique,
  password text not null default '',
  avatar_url text not null default '',
  bio text not null default ''
);

create table if not exists public.goals (
  id bigint primary key,
  sort_order bigint not null default 0,
  data jsonb not null
);

create table if not exists public.ideas (
  id bigint primary key,
  sort_order bigint not null default 0,
  data jsonb not null
);

create table if not exists public.calendar_events (
  id bigint primary key,
  sort_order bigint not null default 0,
  data jsonb not null
);

create table if not exists public.history_events (
  id bigint primary key,
  sort_order bigint not null default 0,
  data jsonb not null
);

create table if not exists public.story_logs (
  id bigint primary key,
  sort_order bigint not null default 0,
  data jsonb not null
);

create table if not exists public.posts (
  id bigint primary key,
  sort_order bigint not null default 0,
  data jsonb not null
);

create table if not exists public.calendar_day_metrics (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  metric_date date not null,
  views integer not null default 0,
  reach integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint calendar_day_metrics_views_nonnegative check (views >= 0),
  constraint calendar_day_metrics_reach_nonnegative check (reach >= 0),
  constraint calendar_day_metrics_user_date_unique unique (user_id, metric_date)
);

create table if not exists public.story_goal_metrics (
  user_id uuid not null references auth.users (id) on delete cascade,
  month_key text not null,
  category text not null check (category in ('total', 'video', 'photo')),
  current_value integer not null default 0,
  goal_value integer not null default 0,
  updated_at timestamptz not null default now(),
  primary key (user_id, month_key, category)
);

create table if not exists public.story_metrics (
  user_id uuid not null references auth.users (id) on delete cascade,
  month_key text not null,
  metric text not null check (metric in ('views', 'reach')),
  value integer not null default 0,
  updated_at timestamptz not null default now(),
  primary key (user_id, month_key, metric)
);

create table if not exists public.shared_state (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.app_preferences (
  user_id uuid not null,
  key text not null,
  value jsonb not null,
  updated_at timestamptz not null default now(),
  primary key (user_id, key)
);

create table if not exists backup.team_profiles (like public.team_profiles including all);
create table if not exists backup.goals (like public.goals including all);
create table if not exists backup.ideas (like public.ideas including all);
create table if not exists backup.calendar_events (like public.calendar_events including all);
create table if not exists backup.history_events (like public.history_events including all);
create table if not exists backup.story_logs (like public.story_logs including all);
create table if not exists backup.posts (like public.posts including all);
create table if not exists backup.calendar_day_metrics (like public.calendar_day_metrics including all);
create table if not exists backup.story_goal_metrics (like public.story_goal_metrics including all);
create table if not exists backup.story_metrics (like public.story_metrics including all);
create table if not exists backup.shared_state (like public.shared_state including all);
create table if not exists backup.app_preferences (like public.app_preferences including all);

insert into backup.team_profiles
select * from public.team_profiles
on conflict do nothing;

insert into backup.goals
select * from public.goals
on conflict do nothing;

insert into backup.ideas
select * from public.ideas
on conflict do nothing;

insert into backup.calendar_events
select * from public.calendar_events
on conflict do nothing;

insert into backup.history_events
select * from public.history_events
on conflict do nothing;

insert into backup.story_logs
select * from public.story_logs
on conflict do nothing;

insert into backup.posts
select * from public.posts
on conflict do nothing;

insert into backup.calendar_day_metrics
select * from public.calendar_day_metrics
on conflict do nothing;

insert into backup.story_goal_metrics
select * from public.story_goal_metrics
on conflict do nothing;

insert into backup.story_metrics
select * from public.story_metrics
on conflict do nothing;

insert into backup.shared_state
select * from public.shared_state
on conflict do nothing;

insert into backup.app_preferences
select * from public.app_preferences
on conflict do nothing;

alter table public.team_profiles enable row level security;
alter table public.goals enable row level security;
alter table public.ideas enable row level security;
alter table public.calendar_events enable row level security;
alter table public.history_events enable row level security;
alter table public.story_logs enable row level security;
alter table public.posts enable row level security;
alter table public.calendar_day_metrics enable row level security;
alter table public.story_goal_metrics enable row level security;
alter table public.story_metrics enable row level security;
alter table public.shared_state enable row level security;
alter table public.app_preferences enable row level security;

drop policy if exists "team_profiles_authenticated_select" on public.team_profiles;
drop policy if exists "team_profiles_authenticated_insert" on public.team_profiles;
drop policy if exists "team_profiles_authenticated_update" on public.team_profiles;
drop policy if exists "team_profiles_authenticated_delete" on public.team_profiles;

drop policy if exists "goals_authenticated_select" on public.goals;
drop policy if exists "goals_authenticated_insert" on public.goals;
drop policy if exists "goals_authenticated_update" on public.goals;
drop policy if exists "goals_authenticated_delete" on public.goals;

drop policy if exists "ideas_authenticated_select" on public.ideas;
drop policy if exists "ideas_authenticated_insert" on public.ideas;
drop policy if exists "ideas_authenticated_update" on public.ideas;
drop policy if exists "ideas_authenticated_delete" on public.ideas;

drop policy if exists "calendar_events_authenticated_select" on public.calendar_events;
drop policy if exists "calendar_events_authenticated_insert" on public.calendar_events;
drop policy if exists "calendar_events_authenticated_update" on public.calendar_events;
drop policy if exists "calendar_events_authenticated_delete" on public.calendar_events;

drop policy if exists "history_events_authenticated_select" on public.history_events;
drop policy if exists "history_events_authenticated_insert" on public.history_events;
drop policy if exists "history_events_authenticated_update" on public.history_events;
drop policy if exists "history_events_authenticated_delete" on public.history_events;

drop policy if exists "story_logs_authenticated_select" on public.story_logs;
drop policy if exists "story_logs_authenticated_insert" on public.story_logs;
drop policy if exists "story_logs_authenticated_update" on public.story_logs;
drop policy if exists "story_logs_authenticated_delete" on public.story_logs;

drop policy if exists "posts_authenticated_select" on public.posts;
drop policy if exists "posts_authenticated_insert" on public.posts;
drop policy if exists "posts_authenticated_update" on public.posts;
drop policy if exists "posts_authenticated_delete" on public.posts;

drop policy if exists "calendar_day_metrics_authenticated_select" on public.calendar_day_metrics;
drop policy if exists "calendar_day_metrics_authenticated_insert" on public.calendar_day_metrics;
drop policy if exists "calendar_day_metrics_authenticated_update" on public.calendar_day_metrics;
drop policy if exists "calendar_day_metrics_authenticated_delete" on public.calendar_day_metrics;
drop policy if exists "calendar_day_metrics_select_own" on public.calendar_day_metrics;
drop policy if exists "calendar_day_metrics_insert_own" on public.calendar_day_metrics;
drop policy if exists "calendar_day_metrics_update_own" on public.calendar_day_metrics;
drop policy if exists "calendar_day_metrics_delete_own" on public.calendar_day_metrics;

drop policy if exists "story_goal_metrics_authenticated_select" on public.story_goal_metrics;
drop policy if exists "story_goal_metrics_authenticated_insert" on public.story_goal_metrics;
drop policy if exists "story_goal_metrics_authenticated_update" on public.story_goal_metrics;
drop policy if exists "story_goal_metrics_authenticated_delete" on public.story_goal_metrics;
drop policy if exists "story_goal_metrics_select_own" on public.story_goal_metrics;
drop policy if exists "story_goal_metrics_insert_own" on public.story_goal_metrics;
drop policy if exists "story_goal_metrics_update_own" on public.story_goal_metrics;
drop policy if exists "story_goal_metrics_delete_own" on public.story_goal_metrics;

drop policy if exists "story_metrics_authenticated_select" on public.story_metrics;
drop policy if exists "story_metrics_authenticated_insert" on public.story_metrics;
drop policy if exists "story_metrics_authenticated_update" on public.story_metrics;
drop policy if exists "story_metrics_authenticated_delete" on public.story_metrics;
drop policy if exists "story_metrics_select_own" on public.story_metrics;
drop policy if exists "story_metrics_insert_own" on public.story_metrics;
drop policy if exists "story_metrics_update_own" on public.story_metrics;
drop policy if exists "story_metrics_delete_own" on public.story_metrics;

drop policy if exists "shared_state_authenticated_select" on public.shared_state;
drop policy if exists "shared_state_authenticated_insert" on public.shared_state;
drop policy if exists "shared_state_authenticated_update" on public.shared_state;
drop policy if exists "shared_state_authenticated_delete" on public.shared_state;

drop policy if exists "app_preferences_select_own" on public.app_preferences;
drop policy if exists "app_preferences_insert_own" on public.app_preferences;
drop policy if exists "app_preferences_update_own" on public.app_preferences;
drop policy if exists "app_preferences_delete_own" on public.app_preferences;

create policy "team_profiles_authenticated_select" on public.team_profiles for select using (auth.role() = 'authenticated');
create policy "team_profiles_authenticated_insert" on public.team_profiles for insert with check (auth.role() = 'authenticated');
create policy "team_profiles_authenticated_update" on public.team_profiles for update using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "team_profiles_authenticated_delete" on public.team_profiles for delete using (auth.role() = 'authenticated');

create policy "goals_authenticated_select" on public.goals for select using (auth.role() = 'authenticated');
create policy "goals_authenticated_insert" on public.goals for insert with check (auth.role() = 'authenticated');
create policy "goals_authenticated_update" on public.goals for update using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "goals_authenticated_delete" on public.goals for delete using (auth.role() = 'authenticated');

create policy "ideas_authenticated_select" on public.ideas for select using (auth.role() = 'authenticated');
create policy "ideas_authenticated_insert" on public.ideas for insert with check (auth.role() = 'authenticated');
create policy "ideas_authenticated_update" on public.ideas for update using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "ideas_authenticated_delete" on public.ideas for delete using (auth.role() = 'authenticated');

create policy "calendar_events_authenticated_select" on public.calendar_events for select using (auth.role() = 'authenticated');
create policy "calendar_events_authenticated_insert" on public.calendar_events for insert with check (auth.role() = 'authenticated');
create policy "calendar_events_authenticated_update" on public.calendar_events for update using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "calendar_events_authenticated_delete" on public.calendar_events for delete using (auth.role() = 'authenticated');

create policy "history_events_authenticated_select" on public.history_events for select using (auth.role() = 'authenticated');
create policy "history_events_authenticated_insert" on public.history_events for insert with check (auth.role() = 'authenticated');
create policy "history_events_authenticated_update" on public.history_events for update using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "history_events_authenticated_delete" on public.history_events for delete using (auth.role() = 'authenticated');

create policy "story_logs_authenticated_select" on public.story_logs for select using (auth.role() = 'authenticated');
create policy "story_logs_authenticated_insert" on public.story_logs for insert with check (auth.role() = 'authenticated');
create policy "story_logs_authenticated_update" on public.story_logs for update using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "story_logs_authenticated_delete" on public.story_logs for delete using (auth.role() = 'authenticated');

create policy "posts_authenticated_select" on public.posts for select using (auth.role() = 'authenticated');
create policy "posts_authenticated_insert" on public.posts for insert with check (auth.role() = 'authenticated');
create policy "posts_authenticated_update" on public.posts for update using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "posts_authenticated_delete" on public.posts for delete using (auth.role() = 'authenticated');

create policy "calendar_day_metrics_select_own" on public.calendar_day_metrics for select using (auth.uid() = user_id);
create policy "calendar_day_metrics_insert_own" on public.calendar_day_metrics for insert with check (auth.uid() = user_id);
create policy "calendar_day_metrics_update_own" on public.calendar_day_metrics for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "calendar_day_metrics_delete_own" on public.calendar_day_metrics for delete using (auth.uid() = user_id);

create policy "story_goal_metrics_select_own" on public.story_goal_metrics for select using (auth.uid() = user_id);
create policy "story_goal_metrics_insert_own" on public.story_goal_metrics for insert with check (auth.uid() = user_id);
create policy "story_goal_metrics_update_own" on public.story_goal_metrics for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "story_goal_metrics_delete_own" on public.story_goal_metrics for delete using (auth.uid() = user_id);

create policy "story_metrics_select_own" on public.story_metrics for select using (auth.uid() = user_id);
create policy "story_metrics_insert_own" on public.story_metrics for insert with check (auth.uid() = user_id);
create policy "story_metrics_update_own" on public.story_metrics for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "story_metrics_delete_own" on public.story_metrics for delete using (auth.uid() = user_id);

create policy "shared_state_authenticated_select" on public.shared_state for select using (auth.role() = 'authenticated');
create policy "shared_state_authenticated_insert" on public.shared_state for insert with check (auth.role() = 'authenticated');
create policy "shared_state_authenticated_update" on public.shared_state for update using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "shared_state_authenticated_delete" on public.shared_state for delete using (auth.role() = 'authenticated');

create policy "app_preferences_select_own" on public.app_preferences for select using (auth.uid() = user_id);
create policy "app_preferences_insert_own" on public.app_preferences for insert with check (auth.uid() = user_id);
create policy "app_preferences_update_own" on public.app_preferences for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "app_preferences_delete_own" on public.app_preferences for delete using (auth.uid() = user_id);

grant usage on schema public to authenticated;
grant select, insert, update, delete on public.team_profiles to authenticated;
grant select, insert, update, delete on public.goals to authenticated;
grant select, insert, update, delete on public.ideas to authenticated;
grant select, insert, update, delete on public.calendar_events to authenticated;
grant select, insert, update, delete on public.history_events to authenticated;
grant select, insert, update, delete on public.story_logs to authenticated;
grant select, insert, update, delete on public.posts to authenticated;
grant select, insert, update, delete on public.calendar_day_metrics to authenticated;
grant select, insert, update, delete on public.story_goal_metrics to authenticated;
grant select, insert, update, delete on public.story_metrics to authenticated;
grant select, insert, update, delete on public.shared_state to authenticated;
grant select, insert, update, delete on public.app_preferences to authenticated;

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'team_profiles'
    ) then
      alter publication supabase_realtime add table public.team_profiles;
    end if;

    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'goals'
    ) then
      alter publication supabase_realtime add table public.goals;
    end if;

    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'ideas'
    ) then
      alter publication supabase_realtime add table public.ideas;
    end if;

    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'calendar_events'
    ) then
      alter publication supabase_realtime add table public.calendar_events;
    end if;

    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'history_events'
    ) then
      alter publication supabase_realtime add table public.history_events;
    end if;

    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'story_logs'
    ) then
      alter publication supabase_realtime add table public.story_logs;
    end if;

    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'posts'
    ) then
      alter publication supabase_realtime add table public.posts;
    end if;

    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'calendar_day_metrics'
    ) then
      alter publication supabase_realtime add table public.calendar_day_metrics;
    end if;

    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'story_goal_metrics'
    ) then
      alter publication supabase_realtime add table public.story_goal_metrics;
    end if;

    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'story_metrics'
    ) then
      alter publication supabase_realtime add table public.story_metrics;
    end if;

    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'shared_state'
    ) then
      alter publication supabase_realtime add table public.shared_state;
    end if;

    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'app_preferences'
    ) then
      alter publication supabase_realtime add table public.app_preferences;
    end if;
  end if;
end
$$;

commit;
