-- Deprecated.
-- Do not apply the historical version of this script because it used permissive
-- policies such as using (true) / with check (true), which break tenant isolation.
--
-- Use these scripts instead:
-- - supabase/shared_state_user_scope.sql
-- - supabase/stories_persistence_fix.sql
-- - supabase/relational_persistence_foundation.sql
-- - supabase/monthly_cycle.sql
