-- Great Organico
-- Restore calendar_events from CSV without Cypress rows.
-- Safe: inserts only the records present in the CSV and skips existing IDs.

begin;

insert into public.calendar_events (id, sort_order, data)
values (1, 0, convert_from(decode('eyJpZCI6MSwiZGF0ZSI6IjIwMjYtMDQtMzAiLCJ0aW1lIjoiMDk6MDAiLCJ0eXBlIjoiU3RvcmllcyIsInRpdGxlIjoiQWxpbmhhbWVudG8gZGUgc3RvcmllcyBkbyBtZXMiLCJzdGF0dXMiOiJBZ2VuZGFkbyIsImNoZWNrbGlzdCI6W3siaWQiOiJjYWxlbmRhci0xLTEiLCJkb25lIjp0cnVlLCJsYWJlbCI6IkRlZmluaXIgcGF1dGEifSx7ImlkIjoiY2FsZW5kYXItMS0yIiwiZG9uZSI6ZmFsc2UsImxhYmVsIjoiU2VwYXJhciByZXNwb25zYXZlaXMifSx7ImlkIjoiY2FsZW5kYXItMS0zIiwiZG9uZSI6ZmFsc2UsImxhYmVsIjoiQ29uZmlybWFyIGhvcmFyaW8ifV0sImRlc2NyaXB0aW9uIjoiQnJlbmRhLCBIYW5uYWggZSBUaGlhZ28gZmVjaGFtIG8gcGxhbm8gcGFyYSBiYXRlciAxNjggc3RvcmllcyBubyBwZXJpb2RvLiIsInJlc3BvbnNpYmxlSWQiOjEsInJlc3BvbnNpYmxlSWRzIjpbMSwyLDNdfQ==', 'base64'), 'UTF8')::jsonb)
on conflict (id) do nothing;

insert into public.calendar_events (id, sort_order, data)
values (2, 1, convert_from(decode('eyJpZCI6MiwiZGF0ZSI6IjIwMjYtMDUtMDEiLCJ0aW1lIjoiMTA6MDAiLCJ0eXBlIjoiUmVlbHMiLCJ0aXRsZSI6IkdyYXZhY2FvIGRlIHJlZWxzIiwic3RhdHVzIjoiRW0gcHJvZHVjYW8iLCJjaGVja2xpc3QiOlt7ImlkIjoiY2FsZW5kYXItMi0xIiwiZG9uZSI6dHJ1ZSwibGFiZWwiOiJHcmF2YXIgYWJlcnR1cmEifSx7ImlkIjoiY2FsZW5kYXItMi0yIiwiZG9uZSI6ZmFsc2UsImxhYmVsIjoiR3JhdmFyIGNlbmFzIGRlIGFwb2lvIn0seyJpZCI6ImNhbGVuZGFyLTItMyIsImRvbmUiOmZhbHNlLCJsYWJlbCI6IlNhbHZhciBiYWNrdXBzIn1dLCJkZXNjcmlwdGlvbiI6IlJvZGFkYSBkZSBjYXB0YWNhbyBwYXJhIG9zIHJlZWxzIGRlIGNvbnZlcnNhbyBkYSBzZW1hbmEuIiwicmVzcG9uc2libGVJZCI6MSwicmVzcG9uc2libGVJZHMiOlsxXX0=', 'base64'), 'UTF8')::jsonb)
on conflict (id) do nothing;

insert into public.calendar_events (id, sort_order, data)
values (3, 2, convert_from(decode('eyJpZCI6MywiZGF0ZSI6IjIwMjYtMDUtMDEiLCJ0aW1lIjoiMTQ6MDAiLCJ0eXBlIjoiQ2Fycm9zc2VsIiwidGl0bGUiOiJSZXZpc2FvIGRvIGNhcnJvc3NlbCIsInN0YXR1cyI6IkFwcm92YWRvIiwiY2hlY2tsaXN0IjpbeyJpZCI6ImNhbGVuZGFyLTMtMSIsImRvbmUiOnRydWUsImxhYmVsIjoiUmV2aXNhciBjb3B5In0seyJpZCI6ImNhbGVuZGFyLTMtMiIsImRvbmUiOnRydWUsImxhYmVsIjoiQ2hlY2FyIGFydGUgZmluYWwifSx7ImlkIjoiY2FsZW5kYXItMy0zIiwiZG9uZSI6ZmFsc2UsImxhYmVsIjoiTGliZXJhciBhZ2VuZGFtZW50byJ9XSwiZGVzY3JpcHRpb24iOiJIYW5uYWggZSBUaGlhZ28gdmFsaWRhbSBhIGFydGUgZSBhIG5hcnJhdGl2YSBhbnRlcyBkZSBwdWJsaWNhci4iLCJyZXNwb25zaWJsZUlkIjozLCJyZXNwb25zaWJsZUlkcyI6WzIsM119', 'base64'), 'UTF8')::jsonb)
on conflict (id) do nothing;

insert into public.calendar_events (id, sort_order, data)
values (4, 3, convert_from(decode('eyJpZCI6NCwiZGF0ZSI6IjIwMjYtMDUtMDIiLCJ0aW1lIjoiMDg6MzAiLCJ0eXBlIjoiU3RvcmllcyIsInRpdGxlIjoiU3RvcmllcyBkZSBjb252ZXJzYW8iLCJzdGF0dXMiOiJQdWJsaWNhZG8iLCJjaGVja2xpc3QiOlt7ImlkIjoiY2FsZW5kYXItNC0xIiwiZG9uZSI6dHJ1ZSwibGFiZWwiOiJWYWxpZGFyIGxlZ2VuZGEifSx7ImlkIjoiY2FsZW5kYXItNC0yIiwiZG9uZSI6dHJ1ZSwibGFiZWwiOiJTdWJpciBzdG9yaWVzIn0seyJpZCI6ImNhbGVuZGFyLTQtMyIsImRvbmUiOmZhbHNlLCJsYWJlbCI6Ik1vbml0b3JhciByZXNwb3N0YXMifV0sImRlc2NyaXB0aW9uIjoiU2VxdWVuY2lhIGN1cnRhIHBhcmEgYXF1ZWNlciBhdWRpZW5jaWEgZSBnZXJhciByZXNwb3N0YSBkaXJldGEuIiwicmVzcG9uc2libGVJZCI6MiwicmVzcG9uc2libGVJZHMiOlsyXX0=', 'base64'), 'UTF8')::jsonb)
on conflict (id) do nothing;

insert into public.calendar_events (id, sort_order, data)
values (5, 4, convert_from(decode('eyJpZCI6NSwiZGF0ZSI6IjIwMjYtMDUtMDMiLCJ0aW1lIjoiMTY6MDAiLCJ0eXBlIjoiRmVlZCIsInRpdGxlIjoiRmVjaGFtZW50byBkbyBjaWNsbyIsInN0YXR1cyI6IkFnZW5kYWRvIiwiY2hlY2tsaXN0IjpbeyJpZCI6ImNhbGVuZGFyLTUtMSIsImRvbmUiOnRydWUsImxhYmVsIjoiRmVjaGFyIHBlbmRlbmNpYXMifSx7ImlkIjoiY2FsZW5kYXItNS0yIiwiZG9uZSI6ZmFsc2UsImxhYmVsIjoiUmV2aXNhciBlbnRyZWdhcyJ9LHsiaWQiOiJjYWxlbmRhci01LTMiLCJkb25lIjpmYWxzZSwibGFiZWwiOiJBZ2VuZGFyIHByb3hpbW9zIHBhc3NvcyJ9XSwiZGVzY3JpcHRpb24iOiJSZXZpc2FvIGZpbmFsIGRhcyBlbnRyZWdhcyBlIHBlbmRlbmNpYXMgcGFyYSBhIHByb3hpbWEgc2VtYW5hLiIsInJlc3BvbnNpYmxlSWQiOjMsInJlc3BvbnNpYmxlSWRzIjpbMSwzXX0=', 'base64'), 'UTF8')::jsonb)
on conflict (id) do nothing;

insert into public.calendar_events (id, sort_order, data)
values (6, 5, convert_from(decode('eyJpZCI6NiwiZGF0ZSI6IjIwMjYtMDUtMjciLCJ0aW1lIjoiMTc6MDAiLCJ0eXBlIjoiU3RvcmllcyIsInRhc2tzIjpbXSwidGl0bGUiOiJYaWNhcmEgZGEgY2xpbmljYSBpbXBvcnRhIiwic3RhdHVzIjoiQWdlbmRhZG8iLCJhZGRlZEJ5SWQiOjEsImNvbXBsZXRlZCI6ZmFsc2UsImRlc2NyaXB0aW9uIjoiVmlkZW8gZGUgc29jaWFsIHNlbGxpbmciLCJyZXNwb25zaWJsZUlkIjoxLCJyZXNwb25zaWJsZUlkcyI6WzFdfQ==', 'base64'), 'UTF8')::jsonb)
on conflict (id) do nothing;

insert into public.calendar_events (id, sort_order, data)
values (7, 6, convert_from(decode('eyJpZCI6NywiZGF0ZSI6IjIwMjYtMDUtMjkiLCJ0aW1lIjoiMDk6MDAiLCJ0eXBlIjoiUmVlbHMiLCJ0YXNrcyI6W10sInRpdGxlIjoiUmV2aXNhciByb3RlaXJvIDE3ODAwNjkzMDk4NDMiLCJzdGF0dXMiOiJBZ2VuZGFkbyIsImFkZGVkQnlJZCI6MiwiZGVzY3JpcHRpb24iOiJBanVzdGFyIG8gcm90ZWlybyBhbnRlcyBkYSBwdWJsaWNhw6fDo28uIiwicmVzcG9uc2libGVJZCI6MiwidmlzdWFsaXphdGlvbiI6IlbDrWRlbyB2aXJhbCIsInJlc3BvbnNpYmxlSWRzIjpbMl19', 'base64'), 'UTF8')::jsonb)
on conflict (id) do nothing;

insert into public.calendar_events (id, sort_order, data)
values (8, 7, convert_from(decode('eyJpZCI6OCwiZGF0ZSI6IjIwMjYtMDUtMjkiLCJ0aW1lIjoiMDk6MDAiLCJ0eXBlIjoiUmVlbHMiLCJ0YXNrcyI6W10sInRpdGxlIjoiUmV2aXNhciByb3RlaXJvIDE3ODAwNjk2Nzk5MTUiLCJzdGF0dXMiOiJBZ2VuZGFkbyIsImFkZGVkQnlJZCI6MiwiZGVzY3JpcHRpb24iOiJBanVzdGFyIG8gcm90ZWlybyBhbnRlcyBkYSBwdWJsaWNhw6fDo28uIiwicmVzcG9uc2libGVJZCI6MiwidmlzdWFsaXphdGlvbiI6IlbDrWRlbyB2aXJhbCIsInJlc3BvbnNpYmxlSWRzIjpbMl19', 'base64'), 'UTF8')::jsonb)
on conflict (id) do nothing;

insert into public.calendar_events (id, sort_order, data)
values (9, 8, convert_from(decode('eyJpZCI6OSwiZGF0ZSI6IjIwMjYtMDUtMjkiLCJ0aW1lIjoiMDk6MDAiLCJ0eXBlIjoiUmVlbHMiLCJ0YXNrcyI6W10sInRpdGxlIjoiUmV2aXNhciByb3RlaXJvIDE3ODAwNzQ2NjM0NzQiLCJzdGF0dXMiOiJBZ2VuZGFkbyIsImFkZGVkQnlJZCI6MiwiZGVzY3JpcHRpb24iOiJBanVzdGFyIG8gcm90ZWlybyBhbnRlcyBkYSBwdWJsaWNhw6fDo28uIiwicmVzcG9uc2libGVJZCI6MiwidmlzdWFsaXphdGlvbiI6IlbDrWRlbyB2aXJhbCIsInJlc3BvbnNpYmxlSWRzIjpbMl19', 'base64'), 'UTF8')::jsonb)
on conflict (id) do nothing;

insert into public.calendar_events (id, sort_order, data)
values (10, 9, convert_from(decode('eyJpZCI6MTAsImRhdGUiOiIyMDI2LTA1LTI5IiwidGltZSI6IjA5OjAwIiwidHlwZSI6IlJlZWxzIiwidGFza3MiOltdLCJ0aXRsZSI6IlJldmlzYXIgcm90ZWlybyAxNzgwMDc1NDMzOTQ2Iiwic3RhdHVzIjoiQWdlbmRhZG8iLCJhZGRlZEJ5SWQiOjIsImRlc2NyaXB0aW9uIjoiQWp1c3RhciBvIHJvdGVpcm8gYW50ZXMgZGEgcHVibGljYcOnw6NvLiIsInJlc3BvbnNpYmxlSWQiOjIsInZpc3VhbGl6YXRpb24iOiJWw61kZW8gdmlyYWwiLCJyZXNwb25zaWJsZUlkcyI6WzJdfQ==', 'base64'), 'UTF8')::jsonb)
on conflict (id) do nothing;

insert into public.calendar_events (id, sort_order, data)
values (11, 10, convert_from(decode('eyJpZCI6MTEsImRhdGUiOiIyMDI2LTA1LTI5IiwidGltZSI6IjA5OjAwIiwidHlwZSI6IlJlZWxzIiwidGFza3MiOltdLCJ0aXRsZSI6IlRhcmVmYSBhbnRpZ2EgMTc4MDA3NTU3MDQ2MyIsInN0YXR1cyI6IkFnZW5kYWRvIiwiYWRkZWRCeUlkIjoxLCJkZXNjcmlwdGlvbiI6IkVzc2EgdGFyZWZhIG7Do28gcG9kZSB2b2x0YXIgZGVwb2lzIGRvIHJlbG9hZC4iLCJyZXNwb25zaWJsZUlkIjoxLCJ2aXN1YWxpemF0aW9uIjoiVsOtZGVvIHZpcmFsIiwicmVzcG9uc2libGVJZHMiOlsxXX0=', 'base64'), 'UTF8')::jsonb)
on conflict (id) do nothing;

insert into public.calendar_events (id, sort_order, data)
values (12, 11, convert_from(decode('eyJpZCI6MTIsImRhdGUiOiIyMDI2LTA1LTI5IiwidGltZSI6IjA5OjAwIiwidHlwZSI6IlJlZWxzIiwidGFza3MiOltdLCJ0aXRsZSI6IlRhcmVmYSBhbnRpZ2EgMTc4MDA3NTgxNTA1NSIsInN0YXR1cyI6IkFnZW5kYWRvIiwiYWRkZWRCeUlkIjoxLCJkZXNjcmlwdGlvbiI6IkVzc2EgdGFyZWZhIG7Do28gcG9kZSB2b2x0YXIgZGVwb2lzIGRvIHJlbG9hZC4iLCJyZXNwb25zaWJsZUlkIjoxLCJ2aXN1YWxpemF0aW9uIjoiVsOtZGVvIHZpcmFsIiwicmVzcG9uc2libGVJZHMiOlsxXX0=', 'base64'), 'UTF8')::jsonb)
on conflict (id) do nothing;

insert into public.calendar_events (id, sort_order, data)
values (13, 12, convert_from(decode('eyJpZCI6MTMsImRhdGUiOiIyMDI2LTA1LTI5IiwidGltZSI6IjA5OjAwIiwidHlwZSI6IlJlZWxzIiwidGFza3MiOltdLCJ0aXRsZSI6IlRhcmVmYSBhbnRpZ2EgMTc4MDA3NTk0MjM5NiIsInN0YXR1cyI6IkFnZW5kYWRvIiwiYWRkZWRCeUlkIjoxLCJkZXNjcmlwdGlvbiI6IkVzc2EgdGFyZWZhIG7Do28gcG9kZSB2b2x0YXIgZGVwb2lzIGRvIHJlbG9hZC4iLCJyZXNwb25zaWJsZUlkIjoxLCJ2aXN1YWxpemF0aW9uIjoiVsOtZGVvIHZpcmFsIiwicmVzcG9uc2libGVJZHMiOlsxXX0=', 'base64'), 'UTF8')::jsonb)
on conflict (id) do nothing;

insert into public.calendar_events (id, sort_order, data)
values (14, 13, convert_from(decode('eyJpZCI6MTQsImRhdGUiOiIyMDI2LTA1LTI5IiwidGltZSI6IjA5OjAwIiwidHlwZSI6IlJlZWxzIiwidGFza3MiOltdLCJ0aXRsZSI6IlRhcmVmYSBhbnRpZ2EgMTc4MDA3NjI0MzQ3NyIsInN0YXR1cyI6IkFnZW5kYWRvIiwiYWRkZWRCeUlkIjoxLCJkZXNjcmlwdGlvbiI6IkVzc2EgdGFyZWZhIG7Do28gcG9kZSB2b2x0YXIgZGVwb2lzIGRvIHJlbG9hZC4iLCJyZXNwb25zaWJsZUlkIjoxLCJ2aXN1YWxpemF0aW9uIjoiVsOtZGVvIHZpcmFsIiwicmVzcG9uc2libGVJZHMiOlsxXX0=', 'base64'), 'UTF8')::jsonb)
on conflict (id) do nothing;

insert into public.calendar_events (id, sort_order, data)
values (15, 14, convert_from(decode('eyJpZCI6MTUsImRhdGUiOiIyMDI2LTA1LTI5IiwidGltZSI6IjA5OjAwIiwidHlwZSI6IlJlZWxzIiwidGFza3MiOltdLCJ0aXRsZSI6IlRhcmVmYSBhbnRpZ2EgMTc4MDA3NjMzNjkwMCIsInN0YXR1cyI6IkFnZW5kYWRvIiwiYWRkZWRCeUlkIjoxLCJkZXNjcmlwdGlvbiI6IkVzc2EgdGFyZWZhIG7Do28gcG9kZSB2b2x0YXIgZGVwb2lzIGRvIHJlbG9hZC4iLCJyZXNwb25zaWJsZUlkIjoxLCJ2aXN1YWxpemF0aW9uIjoiVsOtZGVvIHZpcmFsIiwicmVzcG9uc2libGVJZHMiOlsxXX0=', 'base64'), 'UTF8')::jsonb)
on conflict (id) do nothing;

insert into public.calendar_events (id, sort_order, data)
values (16, 15, convert_from(decode('eyJpZCI6MTYsImRhdGUiOiIyMDI2LTA1LTI5IiwidGltZSI6IjA5OjAwIiwidHlwZSI6IlJlZWxzIiwidGFza3MiOltdLCJ0aXRsZSI6IlRhcmVmYSBub3ZhIDE3ODAwNzYzMzY5MDEiLCJzdGF0dXMiOiJBZ2VuZGFkbyIsImFkZGVkQnlJZCI6MSwiZGVzY3JpcHRpb24iOiJOb3ZhIHRhcmVmYSBjcmlhZGEgZGVwb2lzIGRhIGxpbXBlemEuIiwicmVzcG9uc2libGVJZCI6MSwidmlzdWFsaXphdGlvbiI6IlbDrWRlbyB2aXJhbCIsInJlc3BvbnNpYmxlSWRzIjpbMV19', 'base64'), 'UTF8')::jsonb)
on conflict (id) do nothing;

insert into public.calendar_events (id, sort_order, data)
values (17, 16, convert_from(decode('eyJpZCI6MTcsImRhdGUiOiIyMDI2LTA1LTI5IiwidGltZSI6IjA5OjAwIiwidHlwZSI6IlJlZWxzIiwidGFza3MiOltdLCJ0aXRsZSI6IlJldmlzYXIgcm90ZWlybyAxNzgwMDc2Mzg3NjQzIiwic3RhdHVzIjoiQWdlbmRhZG8iLCJhZGRlZEJ5SWQiOjIsImRlc2NyaXB0aW9uIjoiQWp1c3RhciBvIHJvdGVpcm8gYW50ZXMgZGEgcHVibGljYcOnw6NvLiIsInJlc3BvbnNpYmxlSWQiOjIsInZpc3VhbGl6YXRpb24iOiJWw61kZW8gdmlyYWwiLCJyZXNwb25zaWJsZUlkcyI6WzJdfQ==', 'base64'), 'UTF8')::jsonb)
on conflict (id) do nothing;

insert into public.calendar_events (id, sort_order, data)
values (29, 28, convert_from(decode('eyJpZCI6MjksImRhdGUiOiIyMDI2LTA2LTAxIiwidGltZSI6IjEzOjAwIiwidHlwZSI6IlJlZWxzIiwidGFza3MiOlt7ImlkIjoidGFzay0xNzgwMzE5MzY1OTg4LXg1bHZtMyIsImRvbmUiOmZhbHNlLCJub3RlIjoiIiwibGFiZWwiOiJ2aXJhbCIsImNoZWNrbGlzdCI6ZmFsc2V9XSwidGl0bGUiOiJ2aXJhbCIsInN0YXR1cyI6IkFnZW5kYWRvIiwiYWRkZWRCeUlkIjozLCJkZXNjcmlwdGlvbiI6ImFzZGEiLCJyZXNwb25zaWJsZUlkIjozLCJ2aXN1YWxpemF0aW9uIjoiVsOtZGVvIHZpcmFsIiwicmVzcG9uc2libGVJZHMiOlszXX0=', 'base64'), 'UTF8')::jsonb)
on conflict (id) do nothing;

insert into public.calendar_events (id, sort_order, data)
values (30, 29, convert_from(decode('eyJpZCI6MzAsImRhdGUiOiIyMDI2LTA2LTAxIiwidGltZSI6IjE0OjAwIiwidHlwZSI6IlJlZWxzIiwidGFza3MiOltdLCJ0aXRsZSI6ImNhcnJvc2VsIiwic3RhdHVzIjoiQWdlbmRhZG8iLCJhZGRlZEJ5SWQiOjMsImRlc2NyaXB0aW9uIjoiZGNmdmNmdmNmIiwicmVzcG9uc2libGVJZCI6MywidmlzdWFsaXphdGlvbiI6IlbDrWRlbyB2aXJhbCIsInJlc3BvbnNpYmxlSWRzIjpbM119', 'base64'), 'UTF8')::jsonb)
on conflict (id) do nothing;

insert into public.calendar_events (id, sort_order, data)
values (31, 30, convert_from(decode('eyJpZCI6MzEsImRhdGUiOiIyMDI2LTA2LTAyIiwidGltZSI6IjExOjAwIiwidHlwZSI6IlJlZWxzIiwidGFza3MiOlt7ImlkIjoidGFzay0xNzgwNDE0MDE0ODk4LTVxem9wNCIsImRvbmUiOnRydWUsIm5vdGUiOiIiLCJsYWJlbCI6IlbDrWRlbyBkbyBQTU1BIiwiY2hlY2tsaXN0Ijp0cnVlfV0sInRpdGxlIjoiVsOtZGVvIFBNTUEgLSBOw7N0aWNpYSIsInN0YXR1cyI6IlB1YmxpY2FkbyIsImFkZGVkQnlJZCI6MywiY29tcGxldGVkIjp0cnVlLCJkZXNjcmlwdGlvbiI6Ik7Ds3RpY2lhIiwicmVzcG9uc2libGVJZCI6MywidmlzdWFsaXphdGlvbiI6IlbDrWRlbyB2aXJhbCIsInJlc3BvbnNpYmxlSWRzIjpbM119', 'base64'), 'UTF8')::jsonb)
on conflict (id) do nothing;

insert into public.calendar_events (id, sort_order, data)
values (32, 31, convert_from(decode('eyJpZCI6MzIsImRhdGUiOiIyMDI2LTA2LTA1IiwidGltZSI6IjEwOjAwIiwidHlwZSI6IlJlZWxzIiwidGFza3MiOlt7ImlkIjoidGFzay0xNzgwNjY0NTM5MTkwLXI0cHdyciIsImRvbmUiOnRydWUsIm5vdGUiOiIiLCJsYWJlbCI6ImNhcnJvc3NlbCAxIiwiY2hlY2tsaXN0IjpmYWxzZX0seyJpZCI6InRhc2stMTc4MDY2NDU0MzA2MS1xZGZoeXoiLCJkb25lIjp0cnVlLCJub3RlIjoiIiwibGFiZWwiOiJjYXJyb3NzZWwgMiIsImNoZWNrbGlzdCI6ZmFsc2V9LHsiaWQiOiJ0YXNrLTE3ODA2NjQ1NDc4NTQtdmZzd3JrIiwiZG9uZSI6dHJ1ZSwibm90ZSI6IiIsImxhYmVsIjoiY2Fycm9zc2VsIDMiLCJjaGVja2xpc3QiOmZhbHNlfSx7ImlkIjoidGFzay0xNzgwNjY0NTUxNzEwLWo3azlqcSIsImRvbmUiOnRydWUsIm5vdGUiOiIiLCJsYWJlbCI6ImNhcnJvc3NlbCA0IiwiY2hlY2tsaXN0IjpmYWxzZX0seyJpZCI6InRhc2stMTc4MDY2NDU1NTY4MS1mamlsaW8iLCJkb25lIjp0cnVlLCJub3RlIjoiIiwibGFiZWwiOiJjYXJyb3NzZWwgNSIsImNoZWNrbGlzdCI6ZmFsc2V9LHsiaWQiOiJ0YXNrLTE3ODA2NjQ1NjI1NDItdnV6a2R6IiwiZG9uZSI6dHJ1ZSwibm90ZSI6IiIsImxhYmVsIjoiY2Fycm9zc2VsIDYiLCJjaGVja2xpc3QiOmZhbHNlfSx7ImlkIjoidGFzay0xNzgwNjg4MDA1MDQ1LTNvbGQ5cSIsImRvbmUiOnRydWUsIm5vdGUiOiIiLCJsYWJlbCI6ImNhcGEiLCJjaGVja2xpc3QiOmZhbHNlfSx7ImlkIjoidGFzay0xNzgwNjg4MDEyOTYyLWhlbnA4dCIsImRvbmUiOnRydWUsIm5vdGUiOiIiLCJsYWJlbCI6ImZyYXNlIGRvbWluZ28iLCJjaGVja2xpc3QiOmZhbHNlfV0sInRpdGxlIjoiRGVtYW5kYSBkbyBkaWEgVGhpYWdvIiwic3RhdHVzIjoiQWdlbmRhZG8iLCJhZGRlZEJ5SWQiOjMsImNvbXBsZXRlZCI6dHJ1ZSwiY29tcGxldGVkQXQiOiIyMDI2LTA2LTA1IiwiZGVzY3JpcHRpb24iOiJjYXJyb3NzZWwgZSBoZWxscyBub3RpY2lhIiwiY29tcGxldGVkQnlJZCI6MywicmVzcG9uc2libGVJZCI6MywidmlzdWFsaXphdGlvbiI6IlbDrWRlbyB2aXJhbCIsInJlc3BvbnNpYmxlSWRzIjpbM119', 'base64'), 'UTF8')::jsonb)
on conflict (id) do nothing;

insert into public.calendar_events (id, sort_order, data)
values (33, 32, convert_from(decode('eyJpZCI6MzMsImRhdGUiOiIyMDI2LTA2LTA4IiwidGltZSI6IjEwOjAwIiwidHlwZSI6IlJlZWxzIiwidGFza3MiOltdLCJ0aXRsZSI6InBvc3QgZGlhIGRvcyBuYW1vcmFkb3MiLCJzdGF0dXMiOiJBZ2VuZGFkbyIsImFkZGVkQnlJZCI6MywiY29tcGxldGVkIjpmYWxzZSwiZGVzY3JpcHRpb24iOiJjcmlhciIsInJlc3BvbnNpYmxlSWQiOjMsInZpc3VhbGl6YXRpb24iOiJWw61kZW8gdmlyYWwiLCJyZXNwb25zaWJsZUlkcyI6WzNdfQ==', 'base64'), 'UTF8')::jsonb)
on conflict (id) do nothing;

commit;
